name: lms-vid-transcode-pip

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: lms-vid-transcode-pip:local
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      WORK_DIR: /work
    volumes:
      - transcode-work:/work

volumes:
  transcode-work: