name: lms-vid-transcode-pip

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: lms-vid-transcode-pip:local
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      WORK_DIR: /work
    volumes:
      - transcode-work:/work
    networks:
      - mtu_fixed_net

volumes:
  transcode-work:

networks:
  mtu_fixed_net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1400"